spring:
  datasource:
    url: jdbc:postgresql://pg-db:5432/oms_db
    username: camilo
    password: camilo123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
