eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: camilo
    password: camilo123

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0 # 100% of requests will be traced
