server:
  port: 3003

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server-keycloak:8443/realms/OMS-realm

rabbitmq:
  queue:
    name: orders-queue
