server:
  port: 3001

# spring:
#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: http://auth-server-keycloak:8443/realms/OMS-realm

management:
  observations:
    key-values:
      application: product-catalog-service
